# Files excluded from Jekyll builds
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - .jekyll-cache

# Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-commonmark
  - jekyll-include-cache


# Gem Settings
author: Filip Zurawski

#Jekyll Settings
sass:
    style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Australia/Sydney

# Collections
#collections:
 # units:
  #  output: true
 # universal_skills:
  #  output: true

# Collections Settings
defaults:
  - scope:
      path: ""
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

# Site settings
encoding: UTF-8
lang: en-AU
title: "Macquarie University"
logo: ""
description: "Welcome to the one-stop lecture notes for Software Technology stream, School of Computing, Macquarie University."
url: "https://softwaretechnologymq.github.io/"
baseurl: "/mq-new/"
repo: "https://github.com/philzurawsky/mq-new"
css_inline: true

# Navigation
navigation:
  - units:
      - name: COMP1000
        url: /comp1000/
        chapters:
          - name: Transition to Processing
            url: /transition_to_processing/
          - name: Primitive Operations
            url: /primitive_operations/
      - name: COMP1010
        url: /comp1010/
  - universal:
      - name: Studying Skills
        url: /studying_skills/


navigation_footer:
  - title: "Macquarie University"
    url: https://mq.edu.au/

fonts:
  preconnect_urls:
  - https://fonts.gstatic.com
  font_urls:
  - https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;700&family=Open+Sans:wght@300;400;700&display=swap

#    font-family: 'Fira Code', monospace;
#    font-family: 'Open Sans', sans-serif;